### ISSUE TITLE
Manual resource creation in GUI failed

### ISSUE THREAD

**Issue by ArnoLWeiss** [enilink/enilink#12]
Adding a reference to a non-existent resource's URI results in unavailable server. No error message returned. Example URI: "http://foo.bar/xyz"

**Comment by kenwenzel** [comment]
The editing support currently expects prefixed names for resources and not URIs. If you want to add an URI then you have to use `<http://...>`. If either the resource does not exist within the RDF store or its type is not compatible with the respective property then you have to add an exclamation mark like `<http://...>!` or `my:unknownResource!`.

But nonetheless, the observed beahviour is a bug because it should handle this error gracefully.

The related exception is:

> java.lang.IllegalArgumentException: Unknown prefix for QName {http}
at net.enilink.komma.edit.properties.ResourceEditingSupport.toURI(ResourceEditingSupport.java:338) ~[bundleFile:?]
at net.enilink.komma.edit.properties.ResourceEditingSupport.toURI(ResourceEditingSupport.java:345) ~[bundleFile:?]
at net.enilink.komma.edit.properties.ResourceEditingSupport.convertEditorValue(ResourceEditingSupport.java:405) ~[bundleFile:?]
at net.enilink.komma.edit.properties.EditingHelper.setValue(EditingHelper.java:173) ~[bundleFile:?]
at net.enilink.platform.lift.snippet.JsonCallHandler$$anonfun$apply$2$$anonfun$applyOrElse$20$$anonfun$10.apply(Edit.scala:251) ~[bundleFile:?]
at net.enilink.platform.lift.snippet.JsonCallHandler$$anonfun$apply$2$$anonfun$applyOrElse$20$$anonfun$10.apply(Edit.scala:250) ~[bundleFile:?]
at scala.Option.map(Option.scala:146) ~[bundleFile:?]
at net.enilink.platform.lift.snippet.JsonCallHandler$$anonfun$apply$2$$anonfun$applyOrElse$20.apply(Edit.scala:250) ~[bundleFile:?]
at net.enilink.platform.lift.snippet.JsonCallHandler$$anonfun$apply$2$$anonfun$applyOrElse$20.apply(Edit.scala:246) ~[bundleFile:?]
at scala.Option.map(Option.scala:146) ~[bundleFile:?]
